//go:build ignore

// Gen compiles shader.hlsl to DXBC with the system's d3dcompiler_47.dll
// and writes shaders.go, so that apps need no shader compiler. It runs on
// Windows: go generate ./internal/gpu/d3d11
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"

	"github.com/egoist/mygo/internal/gpu"
	"github.com/egoist/mygo/internal/gpu/d3d11/internal/compiler"
)

func main() {
	src, err := os.ReadFile("shader.hlsl")
	if err != nil {
		log.Fatal(err)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen.go from shader.hlsl; DO NOT EDIT.\n\n//go:build windows\n\npackage d3d11\n\n")
	fmt.Fprintf(&b, "// shaderSum is the SHA-256 of the shader.hlsl the shaders were compiled\n// from.\nconst shaderSum = %q\n\n", gpu.SourceSum(string(src)))
	for _, s := range []struct{ name, entry, target string }{{"vertexShader", "vs", "vs_4_0"}, {"pixelShader", "ps", "ps_4_0"},
		{"passVertexShader", "passvs", "vs_4_0"}, {"downShader", "downps", "ps_4_0"}, {"blurShader", "blurps", "ps_4_0"}} {
		code, err := compiler.Compile(string(src), s.entry, s.target)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Fprintf(&b, "var %s = []byte{", s.name)
		for i, c := range code {
			if i%16 == 0 {
				b.WriteString("\n\t")
			}
			fmt.Fprintf(&b, "0x%02x, ", c)
		}
		b.WriteString("\n}\n\n")
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("shaders.go", out, 0o644); err != nil {
		log.Fatal(err)
	}
}
