// Code generated by internal/cef/gen from the headers of CEF 154.0.32+g682c378+chromium-154.0.8037.58; DO NOT EDIT.

//go:build linux && (amd64 || arm64)

package cef

// The CEF version the structures come from, the API version they follow
// and the hash libcef reports for it on Linux (cef_api_hash).
const (
	cefVersion = "154.0.32+g682c378+chromium-154.0.8037.58"
	apiVersion = 15400
	apiHash    = "5c8344ae7d7f6421bc801401e35d4dbf6d38e101"
)

// cefBaseRefCounted is cef_base_ref_counted_t.
type cefBaseRefCounted struct {
	size             uintptr
	addRef           uintptr
	release          uintptr
	hasOneRef        uintptr
	hasAtLeastOneRef uintptr
}

// cefApp is cef_app_t.
type cefApp struct {
	base                          cefBaseRefCounted
	onBeforeCommandLineProcessing uintptr
	onRegisterCustomSchemes       uintptr
	getResourceBundleHandler      uintptr
	getBrowserProcessHandler      uintptr
	getRenderProcessHandler       uintptr
}

// cefBrowserProcessHandler is cef_browser_process_handler_t.
type cefBrowserProcessHandler struct {
	base                            cefBaseRefCounted
	onRegisterCustomPreferences     uintptr
	onContextInitialized            uintptr
	onBeforeChildProcessLaunch      uintptr
	onAlreadyRunningAppRelaunch     uintptr
	onScheduleMessagePumpWork       uintptr
	getDefaultClient                uintptr
	getDefaultRequestContextHandler uintptr
}

// cefRenderProcessHandler is cef_render_process_handler_t.
type cefRenderProcessHandler struct {
	base                     cefBaseRefCounted
	onWebKitInitialized      uintptr
	onBrowserCreated         uintptr
	onBrowserDestroyed       uintptr
	getLoadHandler           uintptr
	onContextCreated         uintptr
	onContextReleased        uintptr
	onUncaughtException      uintptr
	onFocusedNodeChanged     uintptr
	onProcessMessageReceived uintptr
}

// cefClient is cef_client_t.
type cefClient struct {
	base                     cefBaseRefCounted
	getAudioHandler          uintptr
	getCommandHandler        uintptr
	getContextMenuHandler    uintptr
	getDialogHandler         uintptr
	getDisplayHandler        uintptr
	getDownloadHandler       uintptr
	getDragHandler           uintptr
	getFindHandler           uintptr
	getFocusHandler          uintptr
	getFrameHandler          uintptr
	getPermissionHandler     uintptr
	getJsdialogHandler       uintptr
	getKeyboardHandler       uintptr
	getLifeSpanHandler       uintptr
	getLoadHandler           uintptr
	getPrintHandler          uintptr
	getRenderHandler         uintptr
	getRequestHandler        uintptr
	onProcessMessageReceived uintptr
}

// cefLifeSpanHandler is cef_life_span_handler_t.
type cefLifeSpanHandler struct {
	base                  cefBaseRefCounted
	onBeforePopup         uintptr
	onBeforePopupAborted  uintptr
	onBeforeDevToolsPopup uintptr
	onAfterCreated        uintptr
	doClose               uintptr
	onBeforeClose         uintptr
}

// cefLoadHandler is cef_load_handler_t.
type cefLoadHandler struct {
	base                 cefBaseRefCounted
	onLoadingStateChange uintptr
	onLoadStart          uintptr
	onLoadEnd            uintptr
	onLoadError          uintptr
}

// cefDisplayHandler is cef_display_handler_t.
type cefDisplayHandler struct {
	base                    cefBaseRefCounted
	onAddressChange         uintptr
	onTitleChange           uintptr
	onFaviconUrlchange      uintptr
	onFullscreenModeChange  uintptr
	onTooltip               uintptr
	onStatusMessage         uintptr
	onConsoleMessage        uintptr
	onAutoResize            uintptr
	onLoadingProgressChange uintptr
	onCursorChange          uintptr
	onMediaAccessChange     uintptr
	onContentsBoundsChange  uintptr
	getRootWindowScreenRect uintptr
}

// cefRequestHandler is cef_request_handler_t.
type cefRequestHandler struct {
	base                           cefBaseRefCounted
	onBeforeBrowse                 uintptr
	onOpenUrlfromTab               uintptr
	getResourceRequestHandler      uintptr
	getAuthCredentials             uintptr
	onCertificateError             uintptr
	onSelectClientCertificate      uintptr
	onRenderViewReady              uintptr
	onRenderProcessUnresponsive    uintptr
	onRenderProcessResponsive      uintptr
	onRenderProcessTerminated      uintptr
	onDocumentAvailableInMainFrame uintptr
}

// cefSchemeHandlerFactory is cef_scheme_handler_factory_t.
type cefSchemeHandlerFactory struct {
	base   cefBaseRefCounted
	create uintptr
}

// cefResourceHandler is cef_resource_handler_t.
type cefResourceHandler struct {
	base               cefBaseRefCounted
	open               uintptr
	processRequest     uintptr
	getResponseHeaders uintptr
	skip               uintptr
	read               uintptr
	readResponse       uintptr
	cancel             uintptr
}

// cefDownloadHandler is cef_download_handler_t.
type cefDownloadHandler struct {
	base              cefBaseRefCounted
	canDownload       uintptr
	onBeforeDownload  uintptr
	onDownloadUpdated uintptr
}

// cefPermissionHandler is cef_permission_handler_t.
type cefPermissionHandler struct {
	base                           cefBaseRefCounted
	onRequestMediaAccessPermission uintptr
	onShowPermissionPrompt         uintptr
	onDismissPermissionPrompt      uintptr
}

// cefJsdialogHandler is cef_jsdialog_handler_t.
type cefJsdialogHandler struct {
	base                 cefBaseRefCounted
	onJsdialog           uintptr
	onBeforeUnloadDialog uintptr
	onResetDialogState   uintptr
	onDialogClosed       uintptr
}

// cefDialogHandler is cef_dialog_handler_t.
type cefDialogHandler struct {
	base         cefBaseRefCounted
	onFileDialog uintptr
}

// cefContextMenuHandler is cef_context_menu_handler_t.
type cefContextMenuHandler struct {
	base                   cefBaseRefCounted
	onBeforeContextMenu    uintptr
	runContextMenu         uintptr
	onContextMenuCommand   uintptr
	onContextMenuDismissed uintptr
	runQuickMenu           uintptr
	onQuickMenuCommand     uintptr
	onQuickMenuDismissed   uintptr
}

// cefKeyboardHandler is cef_keyboard_handler_t.
type cefKeyboardHandler struct {
	base          cefBaseRefCounted
	onPreKeyEvent uintptr
	onKeyEvent    uintptr
}

// cefFocusHandler is cef_focus_handler_t.
type cefFocusHandler struct {
	base        cefBaseRefCounted
	onTakeFocus uintptr
	onSetFocus  uintptr
	onGotFocus  uintptr
}

// cefDragHandler is cef_drag_handler_t.
type cefDragHandler struct {
	base                      cefBaseRefCounted
	onDragEnter               uintptr
	onDraggableRegionsChanged uintptr
}

// cefV8Handler is cef_v8_handler_t.
type cefV8Handler struct {
	base    cefBaseRefCounted
	execute uintptr
}

// cefDevToolsMessageObserver is cef_dev_tools_message_observer_t.
type cefDevToolsMessageObserver struct {
	base                    cefBaseRefCounted
	onDevToolsMessage       uintptr
	onDevToolsMethodResult  uintptr
	onDevToolsEvent         uintptr
	onDevToolsAgentAttached uintptr
	onDevToolsAgentDetached uintptr
}

// cefTask is cef_task_t.
type cefTask struct {
	base    cefBaseRefCounted
	execute uintptr
}

// cefDeleteCookiesCallback is cef_delete_cookies_callback_t.
type cefDeleteCookiesCallback struct {
	base       cefBaseRefCounted
	onComplete uintptr
}

// cefBrowser is cef_browser_t.
type cefBrowser struct {
	base                 cefBaseRefCounted
	isValid              uintptr
	getHost              uintptr
	canGoBack            uintptr
	goBack               uintptr
	canGoForward         uintptr
	goForward            uintptr
	isLoading            uintptr
	reload               uintptr
	reloadIgnoreCache    uintptr
	stopLoad             uintptr
	getIdentifier        uintptr
	isSame               uintptr
	isPopup              uintptr
	hasDocument          uintptr
	getMainFrame         uintptr
	getFocusedFrame      uintptr
	getFrameByIdentifier uintptr
	getFrameByName       uintptr
	getFrameCount        uintptr
	getFrameIdentifiers  uintptr
	getFrameNames        uintptr
}

// cefBrowserHost is cef_browser_host_t.
type cefBrowserHost struct {
	base                        cefBaseRefCounted
	getBrowser                  uintptr
	closeBrowser                uintptr
	tryCloseBrowser             uintptr
	isReadyToBeClosed           uintptr
	setFocus                    uintptr
	getWindowHandle             uintptr
	getOpenerWindowHandle       uintptr
	getOpenerIdentifier         uintptr
	hasView                     uintptr
	getClient                   uintptr
	getRequestContext           uintptr
	canZoom                     uintptr
	zoom                        uintptr
	getDefaultZoomLevel         uintptr
	getZoomLevel                uintptr
	setZoomLevel                uintptr
	runFileDialog               uintptr
	startDownload               uintptr
	downloadImage               uintptr
	print                       uintptr
	printToPdf                  uintptr
	find                        uintptr
	stopFinding                 uintptr
	showDevTools                uintptr
	closeDevTools               uintptr
	hasDevTools                 uintptr
	sendDevToolsMessage         uintptr
	executeDevToolsMethod       uintptr
	addDevToolsMessageObserver  uintptr
	getNavigationEntries        uintptr
	replaceMisspelling          uintptr
	addWordToDictionary         uintptr
	isWindowRenderingDisabled   uintptr
	wasResized                  uintptr
	wasHidden                   uintptr
	notifyScreenInfoChanged     uintptr
	invalidate                  uintptr
	sendExternalBeginFrame      uintptr
	sendKeyEvent                uintptr
	sendMouseClickEvent         uintptr
	sendMouseMoveEvent          uintptr
	sendMouseWheelEvent         uintptr
	sendTouchEvent              uintptr
	sendCaptureLostEvent        uintptr
	notifyMoveOrResizeStarted   uintptr
	getWindowlessFrameRate      uintptr
	setWindowlessFrameRate      uintptr
	imeSetComposition           uintptr
	imeCommitText               uintptr
	imeFinishComposingText      uintptr
	imeCancelComposition        uintptr
	dragTargetDragEnter         uintptr
	dragTargetDragOver          uintptr
	dragTargetDragLeave         uintptr
	dragTargetDrop              uintptr
	dragSourceEndedAt           uintptr
	dragSourceSystemDragEnded   uintptr
	getVisibleNavigationEntry   uintptr
	setAccessibilityState       uintptr
	setAutoResizeEnabled        uintptr
	setAudioMuted               uintptr
	isAudioMuted                uintptr
	isFullscreen                uintptr
	exitFullscreen              uintptr
	canExecuteChromeCommand     uintptr
	executeChromeCommand        uintptr
	isRenderProcessUnresponsive uintptr
	getRuntimeStyle             uintptr
}

// cefFrame is cef_frame_t.
type cefFrame struct {
	base               cefBaseRefCounted
	isValid            uintptr
	undo               uintptr
	redo               uintptr
	cut                uintptr
	copy               uintptr
	paste              uintptr
	pasteAndMatchStyle uintptr
	del                uintptr
	selectAll          uintptr
	viewSource         uintptr
	getSource          uintptr
	getText            uintptr
	loadRequest        uintptr
	loadUrl            uintptr
	executeJavaScript  uintptr
	isMain             uintptr
	isFocused          uintptr
	getName            uintptr
	getIdentifier      uintptr
	getParent          uintptr
	getUrl             uintptr
	getBrowser         uintptr
	getV8Context       uintptr
	visitDom           uintptr
	createUrlrequest   uintptr
	sendProcessMessage uintptr
}

// cefRequest is cef_request_t.
type cefRequest struct {
	base                    cefBaseRefCounted
	isReadOnly              uintptr
	getUrl                  uintptr
	setUrl                  uintptr
	getMethod               uintptr
	setMethod               uintptr
	setReferrer             uintptr
	getReferrerUrl          uintptr
	getReferrerPolicy       uintptr
	getPostData             uintptr
	setPostData             uintptr
	getHeaderMap            uintptr
	setHeaderMap            uintptr
	getHeaderByName         uintptr
	setHeaderByName         uintptr
	set                     uintptr
	getFlags                uintptr
	setFlags                uintptr
	getFirstPartyForCookies uintptr
	setFirstPartyForCookies uintptr
	getResourceType         uintptr
	getTransitionType       uintptr
	getIdentifier           uintptr
}

// cefResponse is cef_response_t.
type cefResponse struct {
	base            cefBaseRefCounted
	isReadOnly      uintptr
	getError        uintptr
	setError        uintptr
	getStatus       uintptr
	setStatus       uintptr
	getStatusText   uintptr
	setStatusText   uintptr
	getMimeType     uintptr
	setMimeType     uintptr
	getCharset      uintptr
	setCharset      uintptr
	getHeaderByName uintptr
	setHeaderByName uintptr
	getHeaderMap    uintptr
	setHeaderMap    uintptr
	getUrl          uintptr
	setUrl          uintptr
}

// cefPostData is cef_post_data_t.
type cefPostData struct {
	base                cefBaseRefCounted
	isReadOnly          uintptr
	hasExcludedElements uintptr
	getElementCount     uintptr
	getElements         uintptr
	removeElement       uintptr
	addElement          uintptr
	removeElements      uintptr
}

// cefPostDataElement is cef_post_data_element_t.
type cefPostDataElement struct {
	base          cefBaseRefCounted
	isReadOnly    uintptr
	setToEmpty    uintptr
	setToFile     uintptr
	setToBytes    uintptr
	getType       uintptr
	getFile       uintptr
	getBytesCount uintptr
	getBytes      uintptr
}

// cefCallback is cef_callback_t.
type cefCallback struct {
	base   cefBaseRefCounted
	cont   uintptr
	cancel uintptr
}

// cefResourceReadCallback is cef_resource_read_callback_t.
type cefResourceReadCallback struct {
	base cefBaseRefCounted
	cont uintptr
}

// cefResourceSkipCallback is cef_resource_skip_callback_t.
type cefResourceSkipCallback struct {
	base cefBaseRefCounted
	cont uintptr
}

// cefProcessMessage is cef_process_message_t.
type cefProcessMessage struct {
	base                  cefBaseRefCounted
	isValid               uintptr
	isReadOnly            uintptr
	copy                  uintptr
	getName               uintptr
	getArgumentList       uintptr
	getSharedMemoryRegion uintptr
}

// cefListValue is cef_list_value_t.
type cefListValue struct {
	base          cefBaseRefCounted
	isValid       uintptr
	isOwned       uintptr
	isReadOnly    uintptr
	isSame        uintptr
	isEqual       uintptr
	copy          uintptr
	setSize       uintptr
	getSize       uintptr
	clear         uintptr
	remove        uintptr
	getType       uintptr
	getValue      uintptr
	getBool       uintptr
	getInt        uintptr
	getDouble     uintptr
	getString     uintptr
	getBinary     uintptr
	getDictionary uintptr
	getList       uintptr
	setValue      uintptr
	setNull       uintptr
	setBool       uintptr
	setInt        uintptr
	setDouble     uintptr
	setString     uintptr
	setBinary     uintptr
	setDictionary uintptr
	setList       uintptr
}

// cefBinaryValue is cef_binary_value_t.
type cefBinaryValue struct {
	base       cefBaseRefCounted
	isValid    uintptr
	isOwned    uintptr
	isSame     uintptr
	isEqual    uintptr
	copy       uintptr
	getRawData uintptr
	getSize    uintptr
	getData    uintptr
}

// cefDictionaryValue is cef_dictionary_value_t.
type cefDictionaryValue struct {
	base          cefBaseRefCounted
	isValid       uintptr
	isOwned       uintptr
	isReadOnly    uintptr
	isSame        uintptr
	isEqual       uintptr
	copy          uintptr
	getSize       uintptr
	clear         uintptr
	hasKey        uintptr
	getKeys       uintptr
	remove        uintptr
	getType       uintptr
	getValue      uintptr
	getBool       uintptr
	getInt        uintptr
	getDouble     uintptr
	getString     uintptr
	getBinary     uintptr
	getDictionary uintptr
	getList       uintptr
	setValue      uintptr
	setNull       uintptr
	setBool       uintptr
	setInt        uintptr
	setDouble     uintptr
	setString     uintptr
	setBinary     uintptr
	setDictionary uintptr
	setList       uintptr
}

// cefValue is cef_value_t.
type cefValue struct {
	base          cefBaseRefCounted
	isValid       uintptr
	isOwned       uintptr
	isReadOnly    uintptr
	isSame        uintptr
	isEqual       uintptr
	copy          uintptr
	getType       uintptr
	getBool       uintptr
	getInt        uintptr
	getDouble     uintptr
	getString     uintptr
	getBinary     uintptr
	getDictionary uintptr
	getList       uintptr
	setNull       uintptr
	setBool       uintptr
	setInt        uintptr
	setDouble     uintptr
	setString     uintptr
	setBinary     uintptr
	setDictionary uintptr
	setList       uintptr
}

// cefCommandLine is cef_command_line_t.
type cefCommandLine struct {
	base                  cefBaseRefCounted
	isValid               uintptr
	isReadOnly            uintptr
	copy                  uintptr
	initFromArgv          uintptr
	initFromString        uintptr
	reset                 uintptr
	getArgv               uintptr
	getCommandLineString  uintptr
	getProgram            uintptr
	setProgram            uintptr
	hasSwitches           uintptr
	hasSwitch             uintptr
	getSwitchValue        uintptr
	getSwitches           uintptr
	appendSwitch          uintptr
	appendSwitchWithValue uintptr
	hasArguments          uintptr
	getArguments          uintptr
	appendArgument        uintptr
	prependWrapper        uintptr
	removeSwitch          uintptr
}

// cefV8Context is cef_v8_context_t.
type cefV8Context struct {
	base          cefBaseRefCounted
	getTaskRunner uintptr
	isValid       uintptr
	getBrowser    uintptr
	getFrame      uintptr
	getGlobal     uintptr
	enter         uintptr
	exit          uintptr
	isSame        uintptr
	eval          uintptr
}

// cefV8Value is cef_v8_value_t.
type cefV8Value struct {
	base                            cefBaseRefCounted
	isValid                         uintptr
	isUndefined                     uintptr
	isNull                          uintptr
	isBool                          uintptr
	isInt                           uintptr
	isUint                          uintptr
	isDouble                        uintptr
	isDate                          uintptr
	isString                        uintptr
	isObject                        uintptr
	isArray                         uintptr
	isArrayBuffer                   uintptr
	isFunction                      uintptr
	isPromise                       uintptr
	isSame                          uintptr
	getBoolValue                    uintptr
	getIntValue                     uintptr
	getUintValue                    uintptr
	getDoubleValue                  uintptr
	getDateValue                    uintptr
	getStringValue                  uintptr
	isUserCreated                   uintptr
	hasException                    uintptr
	getException                    uintptr
	clearException                  uintptr
	willRethrowExceptions           uintptr
	setRethrowExceptions            uintptr
	hasValueBykey                   uintptr
	hasValueByindex                 uintptr
	deleteValueBykey                uintptr
	deleteValueByindex              uintptr
	getValueBykey                   uintptr
	getValueByindex                 uintptr
	setValueBykey                   uintptr
	setValueByindex                 uintptr
	setValueByaccessor              uintptr
	getKeys                         uintptr
	setUserData                     uintptr
	getUserData                     uintptr
	getExternallyAllocatedMemory    uintptr
	adjustExternallyAllocatedMemory uintptr
	getArrayLength                  uintptr
	getArrayBufferReleaseCallback   uintptr
	neuterArrayBuffer               uintptr
	getArrayBufferByteLength        uintptr
	getArrayBufferData              uintptr
	getFunctionName                 uintptr
	getFunctionHandler              uintptr
	executeFunction                 uintptr
	executeFunctionWithContext      uintptr
	resolvePromise                  uintptr
	rejectPromise                   uintptr
}

// cefV8Exception is cef_v8_exception_t.
type cefV8Exception struct {
	base                  cefBaseRefCounted
	getMessage            uintptr
	getSourceLine         uintptr
	getScriptResourceName uintptr
	getLineNumber         uintptr
	getStartPosition      uintptr
	getEndPosition        uintptr
	getStartColumn        uintptr
	getEndColumn          uintptr
}

// cefDownloadItem is cef_download_item_t.
type cefDownloadItem struct {
	base                  cefBaseRefCounted
	isValid               uintptr
	isInProgress          uintptr
	isComplete            uintptr
	isCanceled            uintptr
	isInterrupted         uintptr
	getInterruptReason    uintptr
	getCurrentSpeed       uintptr
	getPercentComplete    uintptr
	getTotalBytes         uintptr
	getReceivedBytes      uintptr
	getStartTime          uintptr
	getEndTime            uintptr
	getFullPath           uintptr
	getId                 uintptr
	getUrl                uintptr
	getOriginalUrl        uintptr
	getSuggestedFileName  uintptr
	getContentDisposition uintptr
	getMimeType           uintptr
	isPaused              uintptr
}

// cefBeforeDownloadCallback is cef_before_download_callback_t.
type cefBeforeDownloadCallback struct {
	base cefBaseRefCounted
	cont uintptr
}

// cefDownloadItemCallback is cef_download_item_callback_t.
type cefDownloadItemCallback struct {
	base   cefBaseRefCounted
	cancel uintptr
	pause  uintptr
	resume uintptr
}

// cefJsdialogCallback is cef_jsdialog_callback_t.
type cefJsdialogCallback struct {
	base cefBaseRefCounted
	cont uintptr
}

// cefFileDialogCallback is cef_file_dialog_callback_t.
type cefFileDialogCallback struct {
	base   cefBaseRefCounted
	cont   uintptr
	cancel uintptr
}

// cefMediaAccessCallback is cef_media_access_callback_t.
type cefMediaAccessCallback struct {
	base   cefBaseRefCounted
	cont   uintptr
	cancel uintptr
}

// cefPermissionPromptCallback is cef_permission_prompt_callback_t.
type cefPermissionPromptCallback struct {
	base cefBaseRefCounted
	cont uintptr
}

// cefDragData is cef_drag_data_t.
type cefDragData struct {
	base               cefBaseRefCounted
	clone              uintptr
	isReadOnly         uintptr
	isLink             uintptr
	isFragment         uintptr
	isFile             uintptr
	getLinkUrl         uintptr
	getLinkTitle       uintptr
	getLinkMetadata    uintptr
	getFragmentText    uintptr
	getFragmentHtml    uintptr
	getFragmentBaseUrl uintptr
	getFileName        uintptr
	getFileContents    uintptr
	getFileNames       uintptr
	getFilePaths       uintptr
	setLinkUrl         uintptr
	setLinkTitle       uintptr
	setLinkMetadata    uintptr
	setFragmentText    uintptr
	setFragmentHtml    uintptr
	setFragmentBaseUrl uintptr
	resetFileContents  uintptr
	addFile            uintptr
	clearFilenames     uintptr
	getImage           uintptr
	getImageHotspot    uintptr
	hasImage           uintptr
}

// cefContextMenuParams is cef_context_menu_params_t.
type cefContextMenuParams struct {
	base                     cefBaseRefCounted
	getXcoord                uintptr
	getYcoord                uintptr
	getTypeFlags             uintptr
	getLinkUrl               uintptr
	getUnfilteredLinkUrl     uintptr
	getSourceUrl             uintptr
	hasImageContents         uintptr
	getTitleText             uintptr
	getPageUrl               uintptr
	getFrameUrl              uintptr
	getFrameCharset          uintptr
	getMediaType             uintptr
	getMediaStateFlags       uintptr
	getSelectionText         uintptr
	getMisspelledWord        uintptr
	getDictionarySuggestions uintptr
	isEditable               uintptr
	isSpellCheckEnabled      uintptr
	getEditStateFlags        uintptr
	isCustomMenu             uintptr
}

// cefMenuModel is cef_menu_model_t.
type cefMenuModel struct {
	base                cefBaseRefCounted
	isSubMenu           uintptr
	clear               uintptr
	getCount            uintptr
	addSeparator        uintptr
	addItem             uintptr
	addCheckItem        uintptr
	addRadioItem        uintptr
	addSubMenu          uintptr
	insertSeparatorAt   uintptr
	insertItemAt        uintptr
	insertCheckItemAt   uintptr
	insertRadioItemAt   uintptr
	insertSubMenuAt     uintptr
	remove              uintptr
	removeAt            uintptr
	getIndexOf          uintptr
	getCommandIdAt      uintptr
	setCommandIdAt      uintptr
	getLabel            uintptr
	getLabelAt          uintptr
	setLabel            uintptr
	setLabelAt          uintptr
	getType             uintptr
	getTypeAt           uintptr
	getGroupId          uintptr
	getGroupIdAt        uintptr
	setGroupId          uintptr
	setGroupIdAt        uintptr
	getSubMenu          uintptr
	getSubMenuAt        uintptr
	isVisible           uintptr
	isVisibleAt         uintptr
	setVisible          uintptr
	setVisibleAt        uintptr
	isEnabled           uintptr
	isEnabledAt         uintptr
	setEnabled          uintptr
	setEnabledAt        uintptr
	isChecked           uintptr
	isCheckedAt         uintptr
	setChecked          uintptr
	setCheckedAt        uintptr
	hasAccelerator      uintptr
	hasAcceleratorAt    uintptr
	setAccelerator      uintptr
	setAcceleratorAt    uintptr
	removeAccelerator   uintptr
	removeAcceleratorAt uintptr
	getAccelerator      uintptr
	getAcceleratorAt    uintptr
	setColor            uintptr
	setColorAt          uintptr
	getColor            uintptr
	getColorAt          uintptr
	setFontList         uintptr
	setFontListAt       uintptr
}

// cefRegistration is cef_registration_t.
type cefRegistration struct {
	base cefBaseRefCounted
}

// cefSharedMemoryRegion is cef_shared_memory_region_t.
type cefSharedMemoryRegion struct {
	base    cefBaseRefCounted
	isValid uintptr
	size    uintptr
	memory  uintptr
}

// cefSharedProcessMessageBuilder is cef_shared_process_message_builder_t.
type cefSharedProcessMessageBuilder struct {
	base    cefBaseRefCounted
	isValid uintptr
	size    uintptr
	memory  uintptr
	build   uintptr
}

// cefRequestContext is cef_request_context_t.
type cefRequestContext struct {
	base                         cefPreferenceManager
	isSame                       uintptr
	isSharingWith                uintptr
	isGlobal                     uintptr
	getHandler                   uintptr
	getCachePath                 uintptr
	getCookieManager             uintptr
	registerSchemeHandlerFactory uintptr
	clearSchemeHandlerFactories  uintptr
	clearCertificateExceptions   uintptr
	clearHttpAuthCredentials     uintptr
	closeAllConnections          uintptr
	resolveHost                  uintptr
	getMediaRouter               uintptr
	getWebsiteSetting            uintptr
	setWebsiteSetting            uintptr
	getContentSetting            uintptr
	setContentSetting            uintptr
	setChromeColorScheme         uintptr
	getChromeColorSchemeMode     uintptr
	getChromeColorSchemeColor    uintptr
	getChromeColorSchemeVariant  uintptr
	addSettingObserver           uintptr
	clearHttpCache               uintptr
}

// cefPreferenceManager is cef_preference_manager_t.
type cefPreferenceManager struct {
	base                  cefBaseRefCounted
	hasPreference         uintptr
	getPreference         uintptr
	getAllPreferences     uintptr
	canSetPreference      uintptr
	setPreference         uintptr
	addPreferenceObserver uintptr
}

// cefCookieManager is cef_cookie_manager_t.
type cefCookieManager struct {
	base            cefBaseRefCounted
	visitAllCookies uintptr
	visitUrlCookies uintptr
	setCookie       uintptr
	deleteCookies   uintptr
	flushStore      uintptr
}

// cefMainArgs is cef_main_args_t.
type cefMainArgs struct {
	argc int32
	argv uintptr
}

// cefSettings is cef_settings_t.
type cefSettings struct {
	size                             uintptr
	noSandbox                        int32
	browserSubprocessPath            cefStringUtf16
	frameworkDirPath                 cefStringUtf16
	mainBundlePath                   cefStringUtf16
	multiThreadedMessageLoop         int32
	externalMessagePump              int32
	windowlessRenderingEnabled       int32
	commandLineArgsDisabled          int32
	cachePath                        cefStringUtf16
	rootCachePath                    cefStringUtf16
	persistSessionCookies            int32
	userAgent                        cefStringUtf16
	userAgentProduct                 cefStringUtf16
	locale                           cefStringUtf16
	logFile                          cefStringUtf16
	logSeverity                      int32
	logItems                         int32
	javascriptFlags                  cefStringUtf16
	resourcesDirPath                 cefStringUtf16
	localesDirPath                   cefStringUtf16
	remoteDebuggingPort              int32
	uncaughtExceptionStackSize       int32
	backgroundColor                  uint32
	acceptLanguageList               cefStringUtf16
	cookieableSchemesList            cefStringUtf16
	cookieableSchemesExcludeDefaults int32
	chromePolicyId                   cefStringUtf16
	chromeAppIconId                  int32
	disableSignalHandlers            int32
	useViewsDefaultPopup             int32
}

// cefStringUtf16 is cef_string_utf16_t.
type cefStringUtf16 struct {
	str    uintptr
	length uintptr
	dtor   uintptr
}

// cefBrowserSettings is cef_browser_settings_t.
type cefBrowserSettings struct {
	size                       uintptr
	windowlessFrameRate        int32
	standardFontFamily         cefStringUtf16
	fixedFontFamily            cefStringUtf16
	serifFontFamily            cefStringUtf16
	sansSerifFontFamily        cefStringUtf16
	cursiveFontFamily          cefStringUtf16
	fantasyFontFamily          cefStringUtf16
	defaultFontSize            int32
	defaultFixedFontSize       int32
	minimumFontSize            int32
	minimumLogicalFontSize     int32
	defaultEncoding            cefStringUtf16
	remoteFonts                int32
	javascript                 int32
	javascriptCloseWindows     int32
	javascriptAccessClipboard  int32
	javascriptDomPaste         int32
	imageLoading               int32
	imageShrinkStandaloneToFit int32
	textAreaResize             int32
	tabToLinks                 int32
	localStorage               int32
	databasesDeprecated        int32
	webgl                      int32
	backgroundColor            uint32
	chromeStatusBubble         int32
	chromeZoomBubble           int32
}

// cefWindowInfo is cef_window_info_t.
type cefWindowInfo struct {
	size                       uintptr
	windowName                 cefStringUtf16
	bounds                     cefRect
	parentWindow               uintptr
	windowlessRenderingEnabled int32
	sharedTextureEnabled       int32
	externalBeginFrameEnabled  int32
	window                     uintptr
	runtimeStyle               int32
}

// cefRect is cef_rect_t.
type cefRect struct {
	x      int32
	y      int32
	width  int32
	height int32
}

// cefPopupFeatures is cef_popup_features_t.
type cefPopupFeatures struct {
	size      uintptr
	x         int32
	xSet      int32
	y         int32
	ySet      int32
	width     int32
	widthSet  int32
	height    int32
	heightSet int32
	isPopup   int32
}

// cefKeyEvent is cef_key_event_t.
type cefKeyEvent struct {
	size                 uintptr
	type_                int32
	modifiers            uint32
	windowsKeyCode       int32
	nativeKeyCode        int32
	isSystemKey          int32
	character            uint16
	unmodifiedCharacter  uint16
	focusOnEditableField int32
}

// cefStringUtf8 is cef_string_utf8_t.
type cefStringUtf8 struct {
	str    uintptr
	length uintptr
	dtor   uintptr
}

// cef_runtime_style_t
const (
	cefRuntimeStyleDefault = 0
	cefRuntimeStyleChrome  = cefRuntimeStyleDefault + 1
	cefRuntimeStyleAlloy   = cefRuntimeStyleChrome + 1
)

// cef_log_severity_t
const (
	logseverityDefault = 0
	logseverityVerbose = logseverityDefault + 1
	logseverityDebug   = logseverityVerbose
	logseverityInfo    = logseverityDebug + 1
	logseverityWarning = logseverityInfo + 1
	logseverityError   = logseverityWarning + 1
	logseverityFatal   = logseverityError + 1
	logseverityDisable = 99
)

// cef_log_items_t
const (
	logItemsDefault       = 0
	logItemsNone          = 1
	logItemsFlagProcessId = 1 << 1
	logItemsFlagThreadId  = 1 << 2
	logItemsFlagTimeStamp = 1 << 3
	logItemsFlagTickCount = 1 << 4
)

// cef_process_id_t
const (
	pidBrowser  = 0
	pidRenderer = pidBrowser + 1
)

// cef_thread_id_t
const (
	tidUi               = 0
	tidFileBackground   = tidUi + 1
	tidFileUserVisible  = tidFileBackground + 1
	tidFileUserBlocking = tidFileUserVisible + 1
	tidProcessLauncher  = tidFileUserBlocking + 1
	tidIo               = tidProcessLauncher + 1
	tidRenderer         = tidIo + 1
	tidNumValues        = tidRenderer + 1
)

// cef_v8_propertyattribute_t
const (
	v8PropertyAttributeNone       = 0
	v8PropertyAttributeReadonly   = 1 << 0
	v8PropertyAttributeDontenum   = 1 << 1
	v8PropertyAttributeDontdelete = 1 << 2
)

// cef_transition_type_t
const (
	ttLink               = 0
	ttExplicit           = ttLink + 1
	ttAutoBookmark       = ttExplicit + 1
	ttAutoSubframe       = ttAutoBookmark + 1
	ttManualSubframe     = ttAutoSubframe + 1
	ttGenerated          = ttManualSubframe + 1
	ttAutoToplevel       = ttGenerated + 1
	ttFormSubmit         = ttAutoToplevel + 1
	ttReload             = ttFormSubmit + 1
	ttKeyword            = ttReload + 1
	ttKeywordGenerated   = ttKeyword + 1
	ttNumValues          = ttKeywordGenerated + 1
	ttSourceMask         = 0xff
	ttBlockedFlag        = 0x00800000
	ttForwardBackFlag    = 0x01000000
	ttDirectLoadFlag     = 0x02000000
	ttHomePageFlag       = 0x04000000
	ttFromApiFlag        = 0x08000000
	ttChainStartFlag     = 0x10000000
	ttChainEndFlag       = 0x20000000
	ttClientRedirectFlag = 0x40000000
	ttServerRedirectFlag = 0x80000000
	ttIsRedirectMask     = 0xc0000000
	ttQualifierMask      = 0xffffff00
)

// cef_termination_status_t
const (
	tsAbnormalTermination = 0
	tsProcessWasKilled    = tsAbnormalTermination + 1
	tsProcessCrashed      = tsProcessWasKilled + 1
	tsProcessOom          = tsProcessCrashed + 1
	tsLaunchFailed        = tsProcessOom + 1
	tsIntegrityFailure    = tsLaunchFailed + 1
	tsNumValues           = tsIntegrityFailure + 1
)

// cef_window_open_disposition_t
const (
	cefWodUnknown             = 0
	cefWodCurrentTab          = cefWodUnknown + 1
	cefWodSingletonTab        = cefWodCurrentTab + 1
	cefWodNewForegroundTab    = cefWodSingletonTab + 1
	cefWodNewBackgroundTab    = cefWodNewForegroundTab + 1
	cefWodNewPopup            = cefWodNewBackgroundTab + 1
	cefWodNewWindow           = cefWodNewPopup + 1
	cefWodSaveToDisk          = cefWodNewWindow + 1
	cefWodOffTheRecord        = cefWodSaveToDisk + 1
	cefWodIgnoreAction        = cefWodOffTheRecord + 1
	cefWodSwitchToTab         = cefWodIgnoreAction + 1
	cefWodNewPictureInPicture = cefWodSwitchToTab + 1
	cefWodNewSplitView        = cefWodNewPictureInPicture + 1
	cefWodNumValues           = cefWodNewSplitView + 1
)

// cef_media_access_permission_types_t
const (
	cefMediaPermissionNone                = 0
	cefMediaPermissionDeviceAudioCapture  = 1 << 0
	cefMediaPermissionDeviceVideoCapture  = 1 << 1
	cefMediaPermissionDesktopAudioCapture = 1 << 2
	cefMediaPermissionDesktopVideoCapture = 1 << 3
)

// cef_permission_request_types_t
const (
	cefPermissionTypeNone                         = 0
	cefPermissionTypeArSession                    = 1 << 0
	cefPermissionTypeCameraPanTiltZoom            = 1 << 1
	cefPermissionTypeCameraStream                 = 1 << 2
	cefPermissionTypeCapturedSurfaceControl       = 1 << 3
	cefPermissionTypeClipboard                    = 1 << 4
	cefPermissionTypeTopLevelStorageAccess        = 1 << 5
	cefPermissionTypeDiskQuota                    = 1 << 6
	cefPermissionTypeLocalFonts                   = 1 << 7
	cefPermissionTypeGeolocation                  = 1 << 8
	cefPermissionTypeHandTracking                 = 1 << 9
	cefPermissionTypeIdentityProvider             = 1 << 10
	cefPermissionTypeIdleDetection                = 1 << 11
	cefPermissionTypeMicStream                    = 1 << 12
	cefPermissionTypeMidiSysex                    = 1 << 13
	cefPermissionTypeMultipleDownloads            = 1 << 14
	cefPermissionTypeNotifications                = 1 << 15
	cefPermissionTypeKeyboardLock                 = 1 << 16
	cefPermissionTypePointerLock                  = 1 << 17
	cefPermissionTypeProtectedMediaIdentifier     = 1 << 18
	cefPermissionTypeRegisterProtocolHandler      = 1 << 19
	cefPermissionTypeStorageAccess                = 1 << 20
	cefPermissionTypeVrSession                    = 1 << 21
	cefPermissionTypeWebAppInstallation           = 1 << 22
	cefPermissionTypeWindowManagement             = 1 << 23
	cefPermissionTypeFileSystemAccess             = 1 << 24
	cefPermissionTypeLocalNetworkAccessDeprecated = 1 << 25
	cefPermissionTypeLocalNetwork                 = 1 << 26
	cefPermissionTypeLoopbackNetwork              = 1 << 27
	cefPermissionTypeSensors                      = 1 << 28
)

// cef_permission_request_result_t
const (
	cefPermissionResultAccept    = 0
	cefPermissionResultDeny      = cefPermissionResultAccept + 1
	cefPermissionResultDismiss   = cefPermissionResultDeny + 1
	cefPermissionResultIgnore    = cefPermissionResultDismiss + 1
	cefPermissionResultNumValues = cefPermissionResultIgnore + 1
)

// cef_jsdialog_type_t
const (
	jsdialogtypeAlert     = 0
	jsdialogtypeConfirm   = jsdialogtypeAlert + 1
	jsdialogtypePrompt    = jsdialogtypeConfirm + 1
	jsdialogtypeNumValues = jsdialogtypePrompt + 1
)

// cef_file_dialog_mode_t
const (
	fileDialogOpen         = 0
	fileDialogOpenMultiple = fileDialogOpen + 1
	fileDialogOpenFolder   = fileDialogOpenMultiple + 1
	fileDialogSave         = fileDialogOpenFolder + 1
	fileDialogNumValues    = fileDialogSave + 1
)

// cef_key_event_type_t
const (
	keyeventRawkeydown = 0
	keyeventKeydown    = keyeventRawkeydown + 1
	keyeventKeyup      = keyeventKeydown + 1
	keyeventChar       = keyeventKeyup + 1
)

// cef_event_flags_t
const (
	eventflagNone                    = 0
	eventflagCapsLockOn              = 1 << 0
	eventflagShiftDown               = 1 << 1
	eventflagControlDown             = 1 << 2
	eventflagAltDown                 = 1 << 3
	eventflagLeftMouseButton         = 1 << 4
	eventflagMiddleMouseButton       = 1 << 5
	eventflagRightMouseButton        = 1 << 6
	eventflagCommandDown             = 1 << 7
	eventflagNumLockOn               = 1 << 8
	eventflagIsKeyPad                = 1 << 9
	eventflagIsLeft                  = 1 << 10
	eventflagIsRight                 = 1 << 11
	eventflagAltgrDown               = 1 << 12
	eventflagIsRepeat                = 1 << 13
	eventflagPrecisionScrollingDelta = 1 << 14
	eventflagScrollByPage            = 1 << 15
)

// cef_postdataelement_type_t
const (
	pdeTypeEmpty     = 0
	pdeTypeBytes     = pdeTypeEmpty + 1
	pdeTypeFile      = pdeTypeBytes + 1
	pdeTypeNumValues = pdeTypeFile + 1
)

// cef_value_type_t
const (
	vtypeInvalid    = 0
	vtypeNull       = vtypeInvalid + 1
	vtypeBool       = vtypeNull + 1
	vtypeInt        = vtypeBool + 1
	vtypeDouble     = vtypeInt + 1
	vtypeString     = vtypeDouble + 1
	vtypeBinary     = vtypeString + 1
	vtypeDictionary = vtypeBinary + 1
	vtypeList       = vtypeDictionary + 1
	vtypeNumValues  = vtypeList + 1
)

// cef_drag_operations_mask_t
const (
	dragOperationNone    = 0
	dragOperationCopy    = 1
	dragOperationLink    = 2
	dragOperationGeneric = 4
	dragOperationPrivate = 8
	dragOperationMove    = 16
	dragOperationDelete  = 32
	dragOperationEvery   = 0xffffffff
)

// cef_menu_id_t
const (
	menuIdBack                     = 100
	menuIdForward                  = 101
	menuIdReload                   = 102
	menuIdReloadNocache            = 103
	menuIdStopload                 = 104
	menuIdUndo                     = 110
	menuIdRedo                     = 111
	menuIdCut                      = 112
	menuIdCopy                     = 113
	menuIdPaste                    = 114
	menuIdPasteMatchStyle          = 115
	menuIdDelete                   = 116
	menuIdSelectAll                = 117
	menuIdFind                     = 130
	menuIdPrint                    = 131
	menuIdViewSource               = 132
	menuIdSpellcheckSuggestion0    = 200
	menuIdSpellcheckSuggestion1    = 201
	menuIdSpellcheckSuggestion2    = 202
	menuIdSpellcheckSuggestion3    = 203
	menuIdSpellcheckSuggestion4    = 204
	menuIdSpellcheckSuggestionLast = 204
	menuIdNoSpellingSuggestions    = 205
	menuIdAddToDictionary          = 206
	menuIdCustomFirst              = 220
	menuIdCustomLast               = 250
	menuIdUserFirst                = 26500
	menuIdUserLast                 = 28500
)

// cef_resultcode_t
const (
	cefResultCodeNormalExit                              = 0
	cefResultCodeKilled                                  = cefResultCodeNormalExit + 1
	cefResultCodeHung                                    = cefResultCodeKilled + 1
	cefResultCodeKilledBadMessage                        = cefResultCodeHung + 1
	cefResultCodeGpuDeadOnArrival                        = cefResultCodeKilledBadMessage + 1
	cefResultCodeChromeFirst                             = cefResultCodeGpuDeadOnArrival + 1
	cefResultCodeBadProcessType                          = 6
	cefResultCodeMissingData                             = 7
	cefResultCodeUnsupportedParam                        = 13
	cefResultCodeProfileInUse                            = 21
	cefResultCodePackExtensionError                      = 22
	cefResultCodeNormalExitProcessNotified               = 24
	cefResultCodeInvalidSandboxState                     = 31
	cefResultCodeCloudPolicyEnrollmentFailed             = 32
	cefResultCodeGpuExitOnContextLost                    = 34
	cefResultCodeNormalExitPackExtensionSuccess          = 36
	cefResultCodeSystemResourceExhausted                 = 37
	cefResultCodeNormalExitAutoDeElevated                = 38
	cefResultCodeTerminatedByOtherProcessOnCommitFailure = 39
	cefResultCodeInvalidIsolatedBrowserProcess           = 40
	cefResultCodeChromeLast                              = 41
	cefResultCodeSandboxFatalFirst                       = 7006
	cefResultCodeSandboxFatalIntegrity                   = cefResultCodeSandboxFatalFirst
	cefResultCodeSandboxFatalDroptoken                   = cefResultCodeSandboxFatalIntegrity + 1
	cefResultCodeSandboxFatalFlushandles                 = cefResultCodeSandboxFatalDroptoken + 1
	cefResultCodeSandboxFatalCachedisable                = cefResultCodeSandboxFatalFlushandles + 1
	cefResultCodeSandboxFatalClosehandles                = cefResultCodeSandboxFatalCachedisable + 1
	cefResultCodeSandboxFatalMitigation                  = cefResultCodeSandboxFatalClosehandles + 1
	cefResultCodeSandboxFatalMemoryExceeded              = cefResultCodeSandboxFatalMitigation + 1
	cefResultCodeSandboxFatalWarmup                      = cefResultCodeSandboxFatalMemoryExceeded + 1
	cefResultCodeSandboxFatalBrokerShutdownHung          = cefResultCodeSandboxFatalWarmup + 1
	cefResultCodeSandboxFatalLast                        = cefResultCodeSandboxFatalBrokerShutdownHung + 1
	cefResultCodeNumValues                               = cefResultCodeSandboxFatalLast + 1
)

// cef_focus_source_t
const (
	focusSourceNavigation = 0
	focusSourceSystem     = focusSourceNavigation + 1
	focusSourceNumValues  = focusSourceSystem + 1
)

// cef_resource_type_t
const (
	rtMainFrame                  = 0
	rtSubFrame                   = rtMainFrame + 1
	rtStylesheet                 = rtSubFrame + 1
	rtScript                     = rtStylesheet + 1
	rtImage                      = rtScript + 1
	rtFontResource               = rtImage + 1
	rtSubResource                = rtFontResource + 1
	rtObject                     = rtSubResource + 1
	rtMedia                      = rtObject + 1
	rtWorker                     = rtMedia + 1
	rtSharedWorker               = rtWorker + 1
	rtPrefetch                   = rtSharedWorker + 1
	rtFavicon                    = rtPrefetch + 1
	rtXhr                        = rtFavicon + 1
	rtPing                       = rtXhr + 1
	rtServiceWorker              = rtPing + 1
	rtCspReport                  = rtServiceWorker + 1
	rtPluginResource             = rtCspReport + 1
	rtNavigationPreloadMainFrame = 19
	rtNavigationPreloadSubFrame  = rtNavigationPreloadMainFrame + 1
	rtNumValues                  = rtNavigationPreloadSubFrame + 1
)
