#!/usr/bin/env python3
"""Regenerate native UI locale data. Python is generation tooling only.

CLDR archives are versioned and checked by SHA-256. Chromium translations
are read at an immutable commit. No upstream code is executed.
"""
import concurrent.futures
import hashlib
import io
import json
from pathlib import Path
import re
import tarfile
import time
import urllib.request
import urllib.error
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
VERSION = "48.2.0"
CHROMIUM = "0fb6e7c804f5c3191ec838c940e50e223d57b0b9"
WINUI = "bfb0e2afa07627505c87f56d687b0483fe917d53"
HASHES = {
    "core": "5310e0c7a06c1feb83dc8e54c8584bbe0b9c2ea8320172a18d541986b124585d",
    "dates-full": "0256f1cefeca14f7d515be4872dda48fcdd7e75381430f25aafd0143eae5b430",
    "numbers-full": "2d17a1453c559a62112caeed52e0bcfe3cb8539c99d239ae7b7ed4d0827679d9",
}
CACHE = Path.home() / ".cache/mygo/locales"


def fetch(url):
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / hashlib.sha256(url.encode()).hexdigest()
    if not path.exists():
        for attempt in range(3):
            try:
                with urllib.request.urlopen(url, timeout=30) as response:
                    data = response.read()
                break
            except (OSError, urllib.error.URLError):
                if attempt == 2:
                    raise RuntimeError(f"cannot download {url}")
                time.sleep(attempt + 1)
        path.write_bytes(data)
    return path.read_bytes()


def archive(name):
    url = f"https://registry.npmjs.org/cldr-{name}/-/cldr-{name}-{VERSION}.tgz"
    data = fetch(url)
    if hashlib.sha256(data).hexdigest() != HASHES[name]:
        raise ValueError(f"checksum mismatch for {url}")
    with tarfile.open(fileobj=io.BytesIO(data)) as source:
        return {m.name: source.extractfile(m).read() for m in source if m.isfile()}


def write_go(name, maps):
    lines = ["// Code generated by scripts/locales.py; DO NOT EDIT.",
             f"// Unicode CLDR {VERSION}; Chromium {CHROMIUM}; WinUI {WINUI}.",
             "// See locale-data/README.md for sources and licenses.", "package ui", ""]
    for variable, values in maps.items():
        lines.append(f"var {variable} = map[string]string{{")
        for key, value in sorted(values.items()):
            # Go raw literals preserve Unicode and keep generated data readable.
            text = value if isinstance(value, str) else json.dumps(value, ensure_ascii=False, separators=(",", ":"))
            if "`" in text:
                raise ValueError(f"backtick in {variable}/{key}")
            lines.append(f"\t{json.dumps(key)}: `{text}`,")
        lines.append("}\n")
    (ROOT / "ui" / name).write_text("\n".join(lines))


def main():
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
        core, dates, numbers = list(pool.map(archive, HASHES))
    supplemental = lambda name: json.loads(core[f"package/supplemental/{name}.json"])["supplemental"][name]
    weekdays = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
    records = {}
    for path, blob in dates.items():
        if not path.endswith("/ca-gregorian.json"):
            continue
        tag = path.split("/")[2]
        g = json.loads(blob)["main"][tag]["dates"]["calendars"]["gregorian"]
        n = json.loads(numbers[f"package/main/{tag}/numbers.json"])["main"][tag]["numbers"]
        d = json.loads(dates[f"package/main/{tag}/dateFields.json"])["main"][tag]["dates"]["fields"]
        formats = g["dateTimeFormats"]["availableFormats"]
        period = g["dayPeriods"]["format"]["wide"]
        symbols = {}
        for nu in sorted({n["defaultNumberingSystem"], "latn", "arab", "arabext"}):
            key = "symbols-numberSystem-" + nu
            if key in n and "decimal" in n[key]:
                s = n[key]
                symbols[nu] = {k: s[k] for k in ["decimal", "group", "plusSign", "minusSign", "timeSeparator"]}
        records[tag] = {
            "Date": formats["yMd"], "LongDate": g["dateFormats"]["long"], "MonthYear": formats["yMMMM"],
            "Time": g["timeFormats"]["short"], "Time12": formats.get("hm", "h:mm a"), "Time24": formats.get("Hm", "HH:mm"),
            "Months": [g["months"]["format"]["wide"][str(i)] for i in range(1, 13)],
            "StandaloneMonths": [g["months"]["stand-alone"]["wide"][str(i)] for i in range(1, 13)],
            "Days": [g["days"]["stand-alone"]["short"][day] for day in weekdays],
            "WideDays": [g["days"]["format"]["wide"][day] for day in weekdays],
            "Periods": [period["am"], period["pm"]], "Numbering": n["defaultNumberingSystem"], "Symbols": symbols,
            "Grouping": n["decimalFormats-numberSystem-" + n["defaultNumberingSystem"]]["standard"],
            "Hours": d["hour"]["displayName"], "Minutes": d["minute"]["displayName"],
        }
    systems = {k: v["_digits"] for k, v in supplemental("numberingSystems").items() if v["_type"] == "numeric"}
    write_go("locale_data_generated.go", {"localeRecords": records, "localeDigits": systems,
        "localeParents": supplemental("parentLocales")["parentLocale"],
        "localeFirstDays": supplemental("weekData")["firstDay"]})

    # GRIT IDs are the positive 63 bits of the MD5 fingerprint of the
    # source text (+ meaning, when present). This is Chromium's GRIT
    # tools/grit/grit/extern/FP.py and tools/grit/grit/tclib.py algorithm.
    sources = {
        "ui/strings/ui_strings.grd": {
            "Undo": "IDS_APP_UNDO", "Cut": "IDS_APP_CUT", "Copy": "IDS_APP_COPY", "Paste": "IDS_APP_PASTE",
            "Delete": "IDS_APP_DELETE", "Select All": "IDS_APP_SELECT_ALL", "Close": "IDS_APP_ACCNAME_CLOSE",
            "Done": "IDS_MESSAGE_CENTER_SETTINGS_DONE", "Remove": "IDS_CLIPBOARD_HISTORY_DELETE_BUTTON_HOVER_TEXT"},
        "ui/strings/ax_strings.grd": {
            "Previous month": "IDS_AX_CALENDAR_SHOW_PREVIOUS_MONTH", "Next month": "IDS_AX_CALENDAR_SHOW_NEXT_MONTH",
            "hours": "IDS_AX_HOUR_FIELD_TEXT", "minutes": "IDS_AX_MINUTE_FIELD_TEXT", "AM/PM": "IDS_AX_AM_PM_FIELD_TEXT",
            "Hue": "IDS_AX_COLOR_EDIT_HUE", "Hex": "IDS_AX_COLOR_EDIT_HEXADECIMAL", "Opacity": "IDS_AX_COLOR_ALPHA_SLIDER"},
        "third_party/blink/public/strings/blink_strings.grd": {"Clear": "IDS_FORM_CALENDAR_CLEAR"},
        "components/components_strings.grd": {"Previous": "IDS_ACCNAME_PREVIOUS", "Next": "IDS_ACCNAME_NEXT",
            "No matches": "IDS_ACCESSIBLE_FIND_IN_PAGE_NO_RESULTS", "%s of %s": "IDS_ACCESSIBLE_FIND_IN_PAGE_COUNT"},
        "chrome/app/generated_resources.grd": {"Find": "IDS_ACCNAME_FIND", "Black": "IDS_NTP_COLORS_BLACK",
            "Orange": "IDS_NTP_COLORS_ORANGE", "Pink": "IDS_NTP_COLORS_PINK", "Gray": "IDS_NTP_COLORS_GREY",
            "Yellow": "IDS_NTP_WALLPAPER_SEARCH_COLOR_YELLOW_LABEL"},
    }
    catalogs = {}
    jobs = []
    prefix = f"https://raw.githubusercontent.com/chromium/chromium/{CHROMIUM}/"
    for path, mapping in sources.items():
        root = ET.fromstring(fetch(prefix + path))
        if path == "components/components_strings.grd":
            root.append(ET.fromstring(fetch(prefix + "components/find_in_page_strings.grdp")))
        ids = {}
        for message in root.iter("message"):
            if message.attrib.get("name") not in mapping.values():
                continue
            # GRIT fingerprints placeholder names, never examples or $1.
            parts, placeholders = [message.text or ""], []
            for child in message:
                if child.tag == "ph":
                    placeholders.append(child.attrib["name"])
                    parts.append(child.attrib["name"])
                else:
                    parts.append("".join(child.itertext()))
                parts.append(child.tail or "")
            text = " ".join("".join(parts).split())
            fp = int.from_bytes(hashlib.md5(text.encode()).digest()[:8], "big")
            if meaning := message.attrib.get("meaning"):
                fp = (fp << 1) + (1 if fp & (1 << 63) else 0) + int.from_bytes(hashlib.md5(meaning.encode()).digest()[:8], "big")
            key = next(k for k, v in mapping.items() if v == message.attrib["name"])
            ids[str(fp & 0x7fffffffffffffff)] = (key, placeholders)
        for file in root.iter("file"):
            if file.attrib.get("path", "").endswith(".xtb"):
                url = prefix + str(Path(path).parent / file.attrib["path"])
                jobs.append((url, file.attrib["lang"], ids))
    def translate(job):
        url, tag, ids = job
        out = {}
        for translation in ET.fromstring(fetch(url)).iter("translation"):
            if record := ids.get(translation.attrib["id"]):
                key, placeholders = record
                escape = lambda text: text.replace("%", "%%") if placeholders else text
                parts = [escape(translation.text or "")]
                for child in translation:
                    if child.tag == "ph":
                        index = placeholders.index(child.attrib["name"]) + 1
                        parts.append(f"%[{index}]s")
                    parts.append(escape(child.tail or ""))
                text = "".join(parts).strip()
                text = re.sub(r"\(&[^)]\)", "", text).replace("&", "")
                out[key] = text
        return tag, out
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        for tag, strings in pool.map(translate, jobs):
            tag = {"iw": "he", "zh-CN": "zh-Hans", "zh-TW": "zh-Hant"}.get(tag, tag)
            catalogs.setdefault(tag, {}).update(strings)
    # WinUI's MIT-licensed catalogs supply number/range controls and
    # additional color-picker labels. Keep region-specific translations.
    prefix = f"https://raw.githubusercontent.com/microsoft/microsoft-ui-xaml/{WINUI}/"
    resources = {
        "NumberBox": {"Increase": "NumberBoxUpSpinButtonName", "Decrease": "NumberBoxDownSpinButtonName",
            "minimum": "NumberBoxMinimumValueStatus", "maximum": "NumberBoxMaximumValueStatus"},
        "ColorPicker": {"Red": "TextRedLabel", "Green": "TextGreenLabel", "Blue": "TextBlueLabel",
            "Hue": "TextHueLabel", "Opacity": "TextAlphaLabel", "More": "TextMoreButtonLabelCollapsed",
            "Saturation and brightness": "AutomationNameColorSpectrum"},
    }
    jobs = []
    tree = json.loads(fetch(f"https://api.github.com/repos/microsoft/microsoft-ui-xaml/git/trees/{WINUI}?recursive=1"))["tree"]
    for kind, mapping in resources.items():
        start = f"controls/dev/{kind}/Strings/"
        for file in tree:
            path = file["path"]
            if path.startswith(start) and path.endswith("/Resources.resw"):
                jobs.append((prefix+path, path.split("/")[-2], mapping))
    def winui(job):
        url, tag, mapping = job
        source = {d.attrib["name"]: d.findtext("value") for d in ET.fromstring(fetch(url)).iter("data")}
        out = {k: source[v] for k, v in mapping.items() if v in source}
        parts = tag.split("-")
        tag = "-".join([parts[0].lower()] + [p.upper() if len(p) == 2 else p.title() for p in parts[1:]])
        return tag, out
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        for tag, strings in pool.map(winui, jobs):
            catalogs.setdefault(tag, {}).update(strings)
    write_go("locale_strings_generated.go", {"localeCatalogs": catalogs})
    licenses = ROOT / "ui/locale-data"
    licenses.mkdir(exist_ok=True)
    (licenses / "UNICODE-LICENSE").write_bytes(core["package/LICENSE"])
    (licenses / "CHROMIUM-LICENSE").write_bytes(fetch(f"https://raw.githubusercontent.com/chromium/chromium/{CHROMIUM}/LICENSE"))
    (licenses / "WINUI-LICENSE").write_bytes(fetch(prefix + "LICENSE"))
    print(f"Generated {len(records)} CLDR locales and {len(catalogs)} control catalogs")


if __name__ == "__main__":
    main()
